### ISSUE TITLE
AOC with NW 750 

### ISSUE THREAD

**Issue by TimoJohn** [larshp/abapOpenChecks#313] opened 2016-11-03 13:18 UTC
Hello Lars,
looks like all your checks have Issues with 750:

  METHOD get_message_text.

    CLEAR p_text.

    CASE p_code.
      WHEN '001'.
        p_text = 'Add table key or EMPTY KEY'.              "#EC NOTEXT
      WHEN OTHERS.
        ASSERT 0 = 1.
    ENDCASE.

  ENDMETHOD.

Using ATC the message p_code differs, sometimes it is '0001' or '0002' not really clear to me at the moment.  Strange is that with se24 this is no issue. 

As work around I fix all the OTHERS Statements.

**Comment by larshp** [comment] 2016-11-03 14:09
Hi Timo, welcome to github :smile: 

So the error only occurs when the check is run via ATC, and not when run via code inspector in SE24?

**Comment by TimoJohn** [comment] 2016-11-03 14:18
Yes at the time I tested this was the case. 

must have something todo with the SAP Internal Length of P_CODE.   
I updated the classes to use '0001' or in other cases also 4 letters. 

 inform( p_sub_obj_type = c_type_include
                p_sub_obj_name = lv_include1
                p_line         = ls_prev-row
                p_kind         = iv_error_type
                p_test         = c_my_name
                p_code         = '0001'
                p_param_1      = pack( lt_list ) ).

looks like this helps

**Comment by larshp** [comment] 2016-11-03 17:40
Hi,
I've done some testing on a 750 SP1 system, but I cannot reproduce the error, can you help providing additional information on how to reproduce the error?

Do you schedule a ATC run in background, and then it dumps there? Or does it dump when showing the ATC results in the ATC result browser?

Perhaps try changing the check variant to contain less checks, in case they somehow influence each other.

**Comment by TimoJohn** [comment] 2016-11-03 17:51
We are on 750 SP 004 
Run AOC_17 from  ADT ... got this dump:

The issue is that in  p_code  from ADT is 0001  in and in SE80 / or other Tool I have '001' in it. 
From Exclipse I could not start the debugger ... sorry.

I had to fix the isseue again by updating:

METHOD get_message_text.

    CASE p_code.
      WHEN '0001' or '001'.

Now its better ...

**Comment by larshp** [comment] 2016-11-03 17:58
okay, will try from Eclipse tomorrow :smile:

**Comment by larshp** [comment] 2016-11-04 06:46
try again. It turns out that the bad message codes originates from the check superclasses, so now it calls super->get_message_text, I guess these messages are then later removed from the results. 

I would say this is an error in the SAP standard code, but we have to work around the issue.

Thanks for the bug report :smile:

**Comment by TimoJohn** [comment] 2016-11-04 09:22
Yes I also think this is something in SAP Standard for me this looks like if old tools use different SCI classes than ATC / new tools .... but I did not verify this.

**Comment by larshp** [comment] 2016-11-04 09:41
I have updated the code in commit https://github.com/larshp/abapOpenChecks/commit/f0330741c05efabb35063b52e7dc807c3e19923f

can you try installing it and try again?

**Comment by TimoJohn** [comment] 2016-11-04 11:58
Hello Lars,
"Installing ist good .. our DEV system does not have internet access ... so not ABAP GIT with github ...
I will have to fix them manual. But it looks like it works fine.

**Comment by larshp** [comment] 2016-11-04 12:25
you can create it as an offline project and then import https://github.com/larshp/abapOpenChecks/archive/master.zip

see https://github.com/larshp/abapGit/wiki/Installing-a-repository-offline

**Comment by larshp** [comment] 2016-12-25 16:06
solved, closing, feel free to open a new issue if there still are problems

**Closed by larshp** 2016-12-25 16:06 UTC
